-- 코드를 입력하세요
SELECT ORI.FOOD_TYPE, ORI.REST_ID, ORI.REST_NAME, ORI.FAVORITES
FROM REST_INFO AS ORI
    JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE ) AS SRI
    ON ORI.FAVORITES = SRI.MAX_FAVORITES AND ORI.FOOD_TYPE = SRI.FOOD_TYPE
ORDER BY ORI.FOOD_TYPE DESC