-- 코드를 입력하세요
WITH ALL_COUNT AS (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%')

SELECT 
    DATE_FORMAT(OS.SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(OS.SALES_DATE, '%m') AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT * FROM ALL_COUNT), 1) AS PUCHASED_RATIO
FROM USER_INFO AS UI
    JOIN ONLINE_SALE AS OS
    ON UI.USER_ID = OS.USER_ID
WHERE UI.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH