-- 코드를 입력하세요
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
# GROUP BY 월별 자동차 ID 별 
# SELECT 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
# ORDER BY 결과는 월을 기준으로 오름차순 정렬하고, 월이 같다면 자동차 ID를 기준으로 내림차순 정렬해주세요. 
# HAVING 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외해주세요.

WITH SCRCRH
AS (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)

SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10' 
      AND CAR_ID IN (SELECT * FROM SCRCRH)
GROUP BY MONTH, CAR_ID
HAVING RECORDS != 0
ORDER BY MONTH, CAR_ID DESC
