-- 코드를 입력하세요
-- SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
-- FROM ONLINE_SALE N, OFFLINE_SALE F
-- WHERE TO_CHAR(N.SALES_DATE, 'YYYY-MM') = '2022-03'
--     OR TO_CHAR(F.SALES_DATE, 'YYYY-MM') = '2022-03'

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
UNION ALL
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
ORDER BY 1, 2, 3