-- 코드를 입력하세요
SELECT UGU.USER_ID,
       UGU.NICKNAME,
       CONCAT_WS(' ', UGU.CITY, UGU.STREET_ADDRESS1, UGU.STREET_ADDRESS2) AS 전체주소,
       CONCAT_WS('-', SUBSTR(UGU.TLNO, 1, 3), SUBSTR(UGU.TLNO, 4, 4), SUBSTR(UGU.TLNO, -4)) AS 전화번호
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_USER AS UGU
WHERE UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGU.USER_ID DESC
