-- 코드를 입력하세요
# FROM USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 
# WHERE 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 
# SELECT 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 
# ORDER BY 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_USER AS UGU
    ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS UGB, USED_GOODS_USER AS UGU
# WHERE UGU.USER_ID = UGB.WRITER_ID
# GROUP BY UGU.USER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES