-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES AS P
    JOIN (SELECT HOST_ID, COUNT(*) AS C
    FROM PLACES
    GROUP BY HOST_ID
    HAVING C > 1) AS SP
    ON P.HOST_ID = SP.HOST_ID
ORDER BY P.ID