-- 코드를 입력하세요
# CAR_ID 별로 묶고 그 안에서 2022-10-16이 포함되면 대여중 아니면
WITH IS_RENTED AS (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16')
                
SELECT DISTINCT CAR_ID, 
CASE WHEN CAR_ID IN (SELECT * FROM IS_RENTED) THEN '대여중'
     ELSE '대여 가능'
     END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
ORDER BY CAR_ID DESC