-- 코드를 입력하세요
WITH NINETY AS 
    (SELECT DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상'), 
     
     THIRTY AS 
    (SELECT DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상'),
     
     SEVEN AS 
    (SELECT DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
     
SELECT CRCRH.HISTORY_ID,
    CASE
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 90
        THEN FLOOR((DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * 
        CRCC.DAILY_FEE * (1 - (SELECT * FROM NINETY) * 0.01))
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 30
        THEN FLOOR((DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * 
        CRCC.DAILY_FEE * (1 - (SELECT * FROM THIRTY) * 0.01))
        WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 7
        THEN FLOOR((DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * 
        CRCC.DAILY_FEE * (1 - (SELECT * FROM SEVEN) * 0.01))
        ELSE (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) * CRCC.DAILY_FEE
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
    ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC