-- 코드를 작성해주세요
WITH GRADED AS (
    SELECT 
        CASE
            WHEN (D.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE CATEGORY = "Front End")) > 0 AND 
                (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python")) > 0 THEN "A"
            WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#")) > 0 THEN "B"
            WHEN (D.SKILL_CODE & (SELECT BIT_OR(CODE) FROM SKILLCODES WHERE CATEGORY = "Front End")) > 0 THEN "C"
        END AS GRADE, D.ID, D.EMAIL
    FROM DEVELOPERS AS D
)

SELECT GRADE, ID, EMAIL
FROM GRADED
WHERE GRADE IS NOT NULL
ORDER BY 1, 2